import { DataTypes, Model, ModelAttributeColumnOptions, literal } from 'sequelize';

// Ids are generated by Postgres 18 (time-ordered uuidv7), not by the app.
export const idColumn: ModelAttributeColumnOptions = {
  type: DataTypes.UUID,
  primaryKey: true,
  defaultValue: literal('uuidv7()'),
};

// Sequelize returns DECIMAL as a string to avoid precision loss; our dimensions have at most 4 digits.
export function decimalColumn(name: string, precision: number, scale: number): ModelAttributeColumnOptions {
  return {
    type: DataTypes.DECIMAL(precision, scale),
    allowNull: false,
    get(this: Model) {
      return Number(this.getDataValue(name));
    },
  };
}
